"""empty message

Revision ID: 229595bec63a
Revises: a5448e1879a5
Create Date: 2025-02-11 20:51:13.591402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229595bec63a'
down_revision = 'a5448e1879a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('stay', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
