"""empty message

Revision ID: 5233afa66971
Revises: 
Create Date: 2025-01-31 11:20:55.239546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233afa66971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bemanningsplan',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('Start', sa.String(), nullable=False),
    sa.Column('End', sa.String(), nullable=False),
    sa.Column('Monday', sa.Integer(), nullable=False),
    sa.Column('Tuesday', sa.Integer(), nullable=False),
    sa.Column('Wednesday', sa.Integer(), nullable=False),
    sa.Column('Thursday', sa.Integer(), nullable=False),
    sa.Column('Friday', sa.Integer(), nullable=False),
    sa.Column('Saturday', sa.Integer(), nullable=False),
    sa.Column('Sunday', sa.Integer(), nullable=False),
    sa.Column('Week', sa.String(), nullable=False),
    sa.Column('Navn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('døgnrytmeplan',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('Start', sa.String(), nullable=False),
    sa.Column('End', sa.String(), nullable=False),
    sa.Column('Aktivitet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('ppp',
    sa.Column('pppid', sa.Integer(), nullable=False),
    sa.Column('Start', sa.String(), nullable=False),
    sa.Column('End', sa.String(), nullable=False),
    sa.Column('ppp_mon', sa.Integer(), nullable=False),
    sa.Column('ppp_tue', sa.Integer(), nullable=False),
    sa.Column('ppp_wed', sa.Integer(), nullable=False),
    sa.Column('ppp_thu', sa.Integer(), nullable=False),
    sa.Column('ppp_fri', sa.Integer(), nullable=False),
    sa.Column('ppp_sat', sa.Integer(), nullable=False),
    sa.Column('ppp_sun', sa.Integer(), nullable=False),
    sa.Column('Week', sa.String(), nullable=False),
    sa.Column('Navn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pppid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ppp')
    op.drop_table('døgnrytmeplan')
    op.drop_table('bemanningsplan')
    # ### end Alembic commands ###
