"""empty message

Revision ID: a5448e1879a5
Revises: f7d1af62712d
Create Date: 2025-02-09 09:46:23.314253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5448e1879a5'
down_revision = 'f7d1af62712d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bemanningsplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sykehus', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('post', sa.String(), nullable=True))

    with op.batch_alter_table('ppp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sykehus', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('post', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppp', schema=None) as batch_op:
        batch_op.drop_column('post')
        batch_op.drop_column('sykehus')

    with op.batch_alter_table('bemanningsplan', schema=None) as batch_op:
        batch_op.drop_column('post')
        batch_op.drop_column('sykehus')

    # ### end Alembic commands ###
