"""empty message

Revision ID: f2cdd3bdca3b
Revises: 
Create Date: 2025-02-03 14:12:47.364825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cdd3bdca3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bemanningsplan',
    sa.Column('bid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Start', sa.String(), nullable=False),
    sa.Column('End', sa.String(), nullable=False),
    sa.Column('Monday', sa.Integer(), nullable=False),
    sa.Column('Tuesday', sa.Integer(), nullable=False),
    sa.Column('Wednesday', sa.Integer(), nullable=False),
    sa.Column('Thursday', sa.Integer(), nullable=False),
    sa.Column('Friday', sa.Integer(), nullable=False),
    sa.Column('Saturday', sa.Integer(), nullable=False),
    sa.Column('Sunday', sa.Integer(), nullable=False),
    sa.Column('Week', sa.String(), nullable=False),
    sa.Column('Navn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('døgnrytmeplan',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Start', sa.String(), nullable=False),
    sa.Column('End', sa.String(), nullable=False),
    sa.Column('Aktivitet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('ppp',
    sa.Column('pppid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Start', sa.String(), nullable=False),
    sa.Column('End', sa.String(), nullable=False),
    sa.Column('ppp_mon', sa.Integer(), nullable=False),
    sa.Column('ppp_tue', sa.Integer(), nullable=False),
    sa.Column('ppp_wed', sa.Integer(), nullable=False),
    sa.Column('ppp_thu', sa.Integer(), nullable=False),
    sa.Column('ppp_fri', sa.Integer(), nullable=False),
    sa.Column('ppp_sat', sa.Integer(), nullable=False),
    sa.Column('ppp_sun', sa.Integer(), nullable=False),
    sa.Column('Week', sa.String(), nullable=False),
    sa.Column('Navn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pppid')
    )
    op.create_table('sykehusdata',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('År', sa.Integer(), nullable=False),
    sa.Column('Måned', sa.String(), nullable=False),
    sa.Column('Uke', sa.Integer(), nullable=False),
    sa.Column('Dag', sa.String(), nullable=False),
    sa.Column('DatoTid', sa.String(), nullable=False),
    sa.Column('Timer', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=False),
    sa.Column('helg', sa.Integer(), nullable=False),
    sa.Column('Antall_inn_på_post', sa.Float(), nullable=True),
    sa.Column('Antall_pasienter_ut_av_Post', sa.Float(), nullable=True),
    sa.Column('skift_type', sa.String(), nullable=False),
    sa.Column('Belegg', sa.Float(), nullable=True),
    sa.Column('Prediksjoner_pasientstrøm', sa.Float(), nullable=True),
    sa.Column('Prediksjoner_belegg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sykehusdata')
    op.drop_table('ppp')
    op.drop_table('døgnrytmeplan')
    op.drop_table('bemanningsplan')
    # ### end Alembic commands ###
